

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."delete_auth_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
  BEGIN
    -- Delete from auth.users using the service role
    DELETE FROM auth.users WHERE id = OLD.id;
    RETURN OLD;
  END;
  $$;


ALTER FUNCTION "public"."delete_auth_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
BEGIN
  INSERT INTO public.users (id, email, first_name, username)
  VALUES (
    NEW.id, 
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'first_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'username', '')
  );
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
  BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
  END;
  $$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."validate_ingredient_update"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  -- Check if core identifier (name, original_language) remains unchanged
  IF 
    OLD.name IS DISTINCT FROM NEW.name OR 
    OLD.original_language IS DISTINCT FROM NEW.original_language 
  THEN
    RAISE EXCEPTION 'Cannot modify core ingredient identifier';
  END IF;
  
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."validate_ingredient_update"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "is_system" boolean DEFAULT false,
    "created_by" "uuid",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "translated_category" "jsonb"
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."grocery_items" (
    "user_id" "uuid" NOT NULL,
    "name" "text",
    "quantity" "text",
    "unit" "text",
    "source_recipes" "text"[],
    "note" "text",
    "is_plural" boolean DEFAULT false NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."grocery_items" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ingredients" (
    "id" smallint NOT NULL,
    "singular_name" "text" NOT NULL,
    "translated_names" "jsonb",
    "plural_name" "text"
);


ALTER TABLE "public"."ingredients" OWNER TO "postgres";


ALTER TABLE "public"."ingredients" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ingredients_ingredient_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."recipe_categories" (
    "recipe_id" smallint NOT NULL,
    "categoriy_id" "uuid" NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."recipe_categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."recipe_ingredients" (
    "ingredient_id" smallint NOT NULL,
    "unit" "text",
    "quantity" "text",
    "recipe_id" smallint NOT NULL,
    "notes" "text",
    "translated_notes" "jsonb",
    "subheading" "text",
    "order_index" integer DEFAULT 0,
    "is_plural" boolean DEFAULT false NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name_overrides" "jsonb",
    "linked_recipe_id" smallint
);


ALTER TABLE "public"."recipe_ingredients" OWNER TO "postgres";


COMMENT ON COLUMN "public"."recipe_ingredients"."is_plural" IS 'Indicates whether the ingredient name should be displayed in plural form (true) or singular form (false)';



COMMENT ON COLUMN "public"."recipe_ingredients"."name_overrides" IS 'JSONB object storing custom ingredient name translations that override the default translations from the ingredients table. Format: {"en": "custom English name", "de": "custom German name"}';



CREATE TABLE IF NOT EXISTS "public"."recipes" (
    "servings" "text",
    "instructions" "text"[],
    "title" "text" NOT NULL,
    "source" "text",
    "id" smallint NOT NULL,
    "created_at" "date" DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "notes" "text",
    "original_language" "text" DEFAULT 'en'::"text" NOT NULL,
    "translated_recipe" "jsonb",
    "share_token" character varying(255),
    "shared_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone,
    "is_public" boolean DEFAULT false,
    "images" "jsonb" DEFAULT '[]'::"jsonb",
    "slug" "text" GENERATED ALWAYS AS ("lower"("regexp_replace"("title", '[/ ]'::"text", '-'::"text", 'g'::"text"))) STORED NOT NULL
);


ALTER TABLE "public"."recipes" OWNER TO "postgres";


ALTER TABLE "public"."recipes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rezepte_recipe_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_category_preferences" (
    "id" integer NOT NULL,
    "user_id" "uuid" NOT NULL,
    "category_id" "uuid",
    "category_value" "text" NOT NULL,
    "is_visible" boolean DEFAULT true NOT NULL,
    "display_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."user_category_preferences" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."user_category_preferences_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."user_category_preferences_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."user_category_preferences_id_seq" OWNED BY "public"."user_category_preferences"."id";



CREATE TABLE IF NOT EXISTS "public"."user_cooking_times" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "ingredient_name" "text" NOT NULL,
    "cooking_time" "text",
    "soaking_time" "text",
    "section_name" "text",
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "order_index" integer,
    "dry_weight" integer,
    "cooked_weight" integer,
    "translated_cooking_time" "jsonb",
    "original_language" character varying(5) DEFAULT 'en'::character varying NOT NULL
);


ALTER TABLE "public"."user_cooking_times" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" NOT NULL,
    "username" "text" NOT NULL,
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "first_name" "text",
    "preferred_language" "text" DEFAULT 'en'::"text" NOT NULL
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."user_category_preferences" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."user_category_preferences_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."grocery_items"
    ADD CONSTRAINT "grocery_items_id2_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."grocery_items"
    ADD CONSTRAINT "grocery_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ingredients"
    ADD CONSTRAINT "ingredients_name_key" UNIQUE ("singular_name");



ALTER TABLE ONLY "public"."ingredients"
    ADD CONSTRAINT "ingredients_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ingredients"
    ADD CONSTRAINT "ingredients_plural_name_key" UNIQUE ("plural_name");



ALTER TABLE ONLY "public"."recipe_categories"
    ADD CONSTRAINT "recipe_categories_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."recipe_categories"
    ADD CONSTRAINT "recipe_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recipe_ingredients"
    ADD CONSTRAINT "recipe_ingredients_id2_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."recipe_ingredients"
    ADD CONSTRAINT "recipe_ingredients_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recipes"
    ADD CONSTRAINT "recipes_share_token_key" UNIQUE ("share_token");



ALTER TABLE ONLY "public"."recipes"
    ADD CONSTRAINT "rezepte_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."recipes"
    ADD CONSTRAINT "rezepte_recipe_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."user_category_preferences"
    ADD CONSTRAINT "unique_user_category" UNIQUE ("user_id", "category_id");



ALTER TABLE ONLY "public"."recipes"
    ADD CONSTRAINT "unique_user_recipe_title" UNIQUE ("user_id", "title");



ALTER TABLE ONLY "public"."user_category_preferences"
    ADD CONSTRAINT "user_category_preferences_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_cooking_times"
    ADD CONSTRAINT "user_cooking_times_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_username_key" UNIQUE ("username");



CREATE INDEX "idx_recipe_ingredients_name_overrides" ON "public"."recipe_ingredients" USING "gin" ("name_overrides");



CREATE INDEX "idx_recipes_share_token" ON "public"."recipes" USING "btree" ("share_token");



CREATE INDEX "idx_user_category_preferences_display_order" ON "public"."user_category_preferences" USING "btree" ("user_id", "display_order");



CREATE INDEX "idx_user_category_preferences_user_id" ON "public"."user_category_preferences" USING "btree" ("user_id");



CREATE INDEX "idx_user_cooking_times_ingredient_name" ON "public"."user_cooking_times" USING "btree" ("ingredient_name");



CREATE INDEX "idx_user_cooking_times_translations" ON "public"."user_cooking_times" USING "gin" ("translated_cooking_time");



CREATE INDEX "idx_user_cooking_times_user_id" ON "public"."user_cooking_times" USING "btree" ("user_id");



CREATE INDEX "ingredients_translated_names_gin_idx" ON "public"."ingredients" USING "gin" ("translated_names");



CREATE INDEX "recipe_ingredients_translated_notes_gin_idx" ON "public"."recipe_ingredients" USING "gin" ("translated_notes");



CREATE INDEX "recipes_translated_data_gin_idx" ON "public"."recipes" USING "gin" ("translated_recipe");



CREATE OR REPLACE TRIGGER "on_user_delete" AFTER DELETE ON "public"."users" FOR EACH ROW EXECUTE FUNCTION "public"."delete_auth_user"();



CREATE OR REPLACE TRIGGER "update_recipes_updated_at" BEFORE UPDATE ON "public"."recipes" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_user_cooking_times_updated_at" BEFORE UPDATE ON "public"."user_cooking_times" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."grocery_items"
    ADD CONSTRAINT "grocery_lists_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."recipe_categories"
    ADD CONSTRAINT "recipe_categories_categoriy_id_fkey" FOREIGN KEY ("categoriy_id") REFERENCES "public"."categories"("id");



ALTER TABLE ONLY "public"."recipe_categories"
    ADD CONSTRAINT "recipe_categories_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "public"."recipes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."recipe_ingredients"
    ADD CONSTRAINT "recipe_ingredients_ingredient_id_fkey" FOREIGN KEY ("ingredient_id") REFERENCES "public"."ingredients"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."recipe_ingredients"
    ADD CONSTRAINT "recipe_ingredients_linked_recipe_id_fkey" FOREIGN KEY ("linked_recipe_id") REFERENCES "public"."recipes"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."recipe_ingredients"
    ADD CONSTRAINT "recipe_ingredients_recipe_id_fkey" FOREIGN KEY ("recipe_id") REFERENCES "public"."recipes"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."recipes"
    ADD CONSTRAINT "recipes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."user_category_preferences"
    ADD CONSTRAINT "user_category_preferences_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_category_preferences"
    ADD CONSTRAINT "user_category_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_cooking_times"
    ADD CONSTRAINT "user_cooking_times_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Anyone can view system categories" ON "public"."categories" FOR SELECT USING (("is_system" = true));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."ingredients" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."ingredients" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."recipe_ingredients" FOR SELECT USING (true);



CREATE POLICY "Users can create own categories" ON "public"."categories" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"() = "created_by") AND ("is_system" = false)));



CREATE POLICY "Users can create recipe categories" ON "public"."recipe_categories" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."recipes"
  WHERE (("recipes"."id" = "recipe_categories"."recipe_id") AND ("recipes"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can delete recipe categories" ON "public"."recipe_categories" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."recipes"
  WHERE (("recipes"."id" = "recipe_categories"."recipe_id") AND ("recipes"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can delete their own account" ON "public"."users" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can delete their own cooking times" ON "public"."user_cooking_times" FOR DELETE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can delete their own data" ON "public"."recipes" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Users can delete their own recipe ingredients" ON "public"."recipe_ingredients" FOR DELETE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."recipes"
  WHERE (("recipes"."id" = "recipe_ingredients"."recipe_id") AND (( SELECT "auth"."uid"() AS "uid") = "recipes"."user_id")))));



CREATE POLICY "Users can insert their own cooking times" ON "public"."user_cooking_times" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can insert their own data" ON "public"."recipes" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can insert their own profile" ON "public"."users" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can insert their own recipe ingredients" ON "public"."recipe_ingredients" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."recipes"
  WHERE (("recipes"."id" = "recipe_ingredients"."recipe_id") AND (( SELECT "auth"."uid"() AS "uid") = "recipes"."user_id")))));



CREATE POLICY "Users can manage their own category preferences" ON "public"."user_category_preferences" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can manage their own grocery items" ON "public"."grocery_items" TO "authenticated" USING (("user_id" = ( SELECT "auth"."uid"() AS "uid"))) WITH CHECK (("user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can select their own row" ON "public"."users" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can update ingredient
  translations" ON "public"."ingredients" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Users can update own categories" ON "public"."categories" FOR UPDATE TO "authenticated" USING ((("auth"."uid"() = "created_by") AND ("is_system" = false)));



CREATE POLICY "Users can update recipe categories" ON "public"."recipe_categories" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."recipes"
  WHERE (("recipes"."id" = "recipe_categories"."recipe_id") AND ("recipes"."user_id" = "auth"."uid"())))));



CREATE POLICY "Users can update their own cooking times" ON "public"."user_cooking_times" FOR UPDATE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update their own data" ON "public"."recipes" FOR UPDATE TO "authenticated" USING (("user_id" = ( SELECT "auth"."uid"() AS "uid")));



CREATE POLICY "Users can update their own profile" ON "public"."users" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can update their own recipe ingredients" ON "public"."recipe_ingredients" FOR UPDATE TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."recipes"
  WHERE (("recipes"."id" = "recipe_ingredients"."recipe_id") AND (( SELECT "auth"."uid"() AS "uid") = "recipes"."user_id")))));



CREATE POLICY "Users can view all categories" ON "public"."categories" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Users can view recipe categories" ON "public"."recipe_categories" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."recipes"
  WHERE (("recipes"."id" = "recipe_categories"."recipe_id") AND ((("auth"."uid"() IS NULL) AND ("recipes"."user_id" = 'b6c94e14-1c26-42b6-8a0b-75fd7136c5cb'::"uuid")) OR (("auth"."uid"() IS NOT NULL) AND ("recipes"."user_id" = "auth"."uid"())))))));



CREATE POLICY "Users can view their own cooking times" ON "public"."user_cooking_times" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can view their own data when logged in" ON "public"."recipes" FOR SELECT USING ((("auth"."uid"() = "user_id") OR ("is_public" = true)));



ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."grocery_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ingredients" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recipe_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recipe_ingredients" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."recipes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_category_preferences" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_cooking_times" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."delete_auth_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."delete_auth_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."delete_auth_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";



GRANT ALL ON FUNCTION "public"."validate_ingredient_update"() TO "anon";
GRANT ALL ON FUNCTION "public"."validate_ingredient_update"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."validate_ingredient_update"() TO "service_role";


















GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON TABLE "public"."grocery_items" TO "anon";
GRANT ALL ON TABLE "public"."grocery_items" TO "authenticated";
GRANT ALL ON TABLE "public"."grocery_items" TO "service_role";



GRANT ALL ON TABLE "public"."ingredients" TO "anon";
GRANT ALL ON TABLE "public"."ingredients" TO "authenticated";
GRANT ALL ON TABLE "public"."ingredients" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ingredients_ingredient_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ingredients_ingredient_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ingredients_ingredient_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."recipe_categories" TO "anon";
GRANT ALL ON TABLE "public"."recipe_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."recipe_categories" TO "service_role";



GRANT ALL ON TABLE "public"."recipe_ingredients" TO "anon";
GRANT ALL ON TABLE "public"."recipe_ingredients" TO "authenticated";
GRANT ALL ON TABLE "public"."recipe_ingredients" TO "service_role";



GRANT ALL ON TABLE "public"."recipes" TO "anon";
GRANT ALL ON TABLE "public"."recipes" TO "authenticated";
GRANT ALL ON TABLE "public"."recipes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rezepte_recipe_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rezepte_recipe_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rezepte_recipe_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_category_preferences" TO "anon";
GRANT ALL ON TABLE "public"."user_category_preferences" TO "authenticated";
GRANT ALL ON TABLE "public"."user_category_preferences" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_category_preferences_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_category_preferences_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_category_preferences_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_cooking_times" TO "anon";
GRANT ALL ON TABLE "public"."user_cooking_times" TO "authenticated";
GRANT ALL ON TABLE "public"."user_cooking_times" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Users can delete their own recipe images"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'recipe-images'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Users can update their own recipe images"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'recipe-images'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)))
with check (((bucket_id = 'recipe-images'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Users can upload their own recipe images"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'recipe-images'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



  create policy "Users can view their own recipe images"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'recipe-images'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));



